### ISSUE TITLE
Install globus command line interface on Yeti

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/data-life-cycle-cloud-docker-jupyterhub#23]
We want to be able to automatically move model output from Yeti to cloud when the run is finished.

Until now we have used the Globus Web App at https://www.globus.org/app/transfer but we want the [Globus command line interface](https://docs.globus.org/cli/) (globus-cli) so we can add that to the control scripts that run the simulations.

**Comment by rsignell-usgs** [comment]
Thankfully the HCC Conda channel has packaged globus-cli.   So we can install it via:
```
conda env create -f conda-cli.yml
```
where `conda-cli.yml` is:
```yaml
name: globus-cli
channels:
  - hcc
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - globus-cli
```
